plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

permalink: /:title/

defaults:
    -
        scope:
            path: ""
        values:
            layout: default

url: https://mmap.page/micro-gh-page
title: mmap.page
repo: weakish/weakish.github.com