plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

permalink: /:title/

defaults:
    -
        scope:
            path: ""
        values:
            layout: default

url: https://mmap.page
title: Micro GitHub Page
repo: weakish/weakish.github.com