plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

permalink: /:title/

defaults:
    -
        scope:
            path: ""
        values:
            layout: default

url: mmap.page/micro-gh-page
title: Micro GitHub Page
repo: weakish/micro-gh-page